title: BFH
description: BFH | Bern University of Applied Sciences 
theme: minima
header_pages:
  - departemente.md

author: Open Source - Community of Practice

twitter_username: bfh_hesb
github_username: bfh
facebook_username: bernerfachhochschule
instagram_username: berner_fachhochschule
linkedin_username: school/berner-fachhochschule-bfh
youtube_username: BernerFachhochschule
