title: BFH
description: BFH | Bern University of Applied Sciences 
theme: minima
header_pages:
  - departemente.md

author: Open Source - Community of Practice

twitter_username: bfh_hesb
github_username:  bfh
