title: BFH
description: BFH | Bern University of Applied Sciences 
remote_theme: jekyll/minima

author:
  name: BFH - Open Source Community of Practice
  email: opensource@bfh.ch

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar

header_pages:
  - use.md 
  - contribute.md
  - contact.md

future: true

minima:
  skin: classic
  date_format: "%d.%m.%Y"
  social_links:
    - title: BFH organization at GitHub
      icon: github
      url: "https://github.com/bfh/"
    - title: BFH organization at LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/school/berner-fachhochschule-bfh/"
    - title: BFH organization at X
      icon: twitter
      url: "https://twitter.com/bfh_hesb"
    - title: BFH organization at YouTube
      icon: youtube
      url: "https://www.youtube.com/@BernerFachhochschule"
