title: BFH
description: BFH | Bern University of Applied Sciences 
remote_theme: jekyll/minima

author:
  name: BFH - Communities of Practice
  email: opensource@bfh.ch

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar

header_pages:
  - cop-opensource.md

future: true

minima:
  skin: classic
  date_format: "%d.%m.%Y"
  social_links:
    - { platform: github, user_url: "https://github.com/bfh/" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/school/berner-fachhochschule-bfh/" }
    - { platform: twitter, user_url: "https://twitter.com/bfh_hesb" }
    - { platform: youtube, user_url: "https://www.youtube.com/@BernerFachhochschule" }
