source "https://rubygems.org"

gem "minima", git: "https://github.com/jekyll/minima"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem 'jekyll-sitemap'
  gem 'jekyll-seo-tag'
  gem 'jekyll-remote-theme'
  gem "jekyll-avatar", "~> 0.7.0"
end
